backend:
  name: test-repo
  repo: keolasin/personal-revamp
  branch: master
  
publish_mode: editorial_workflow

media_library:
  name: cloudinary
  config:
    cloud_name: keolasin
    api_key: 267523381728576

media_folder: static/assets
public_folder: /assets

collections:
  - name: mainPages
    label: Main Pages
    dsecription: Main pages such as home page, contact
    files: 
      - file: src/pages/index.md
        label: Home page
        name: index
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: index-page }
          - { name: title, label: Title, widget: string }
          - { name: thumbnailImg, label: Thumbnail Image, widget: image }
          - { name: heading, label: Heading, widget: string }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/contact.md
        label: Contact Page
        name: contact
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: contact-page }
          - { name: title, label: Title, widget: string }
          - { name: thumbnailImg, label: Thumbnail Image, widget: image }
          - { name: heading, label: Heading, widget: string }
          - { name: body, label: Body, widget: markdown }
          - name: socialLinks
            label: Social Media Links
            widget: list
            fields:
              - { name: website, label: Website Name, widget: string, hint: The name of the site (ex mreyes) }
              - { name: link, label: Website Link, widget: string, hint: The website url (ex www.mreyes.info) }

  - name: projects
    label: Projects
    label_singular: Project
    description: A project with a short summary and image about it, with a link to a live demo, code repo, and/or longer article.
    folder: src/pages/projects
    preview_path: "projects/{{slug}}"
    create: true
    view_filters:
      - label: Projects with index
        field: title
        pattern: This is project #
      - label: Projects without index
        field: title
        pattern: front matter project
      - label: Drafts
        field: draft
        pattern: true
    fields:
        - { name: title, label: Title }
        - { name: draft, label: Draft, widget: boolean, default: true }
        - { name: date, label: Date, widget: date, dateFormat: MM-DD-YYYY }
        - { name: link, label: Link, widget: string, hint: Link to the live site/demo }
        - { name: body, label: Body, widget: markdown, hint: Main content goes here }
        - { name: image, label: Cover image, widget: image, required: false }
        - { name: imageAlt, label: Image Alt Text, widget: string, required: false, hint: Alternate text to show when an image cannot be loaded or displayed }

  - name: albums
    label: Albums
    label_singular: Album
    description: A photo album showing it's title, the photos in the album, and a short description about the album.
    folder: src/pages/albums
    create: true
    preview_path: "/albums/{{albums}}"
    fields:
      - { name: title, label: Title }
      - { name: photographer, label: Photographer }
      - { name: date, label: Date, widget: date }
      - { name: coverImg, label: Cover Image, widget: image }
      - { name: description, label: Description, widget: string }
      - name: photos
        label: Photos
        widget: list
        fields:
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: date, label: Date, widget: date }
          - { name: imageAlt, label: Image Alternate Text, widget: string, required: false, hint: Alternate text to show when an image cannot be loaded or displayed }